version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evolution
      # MYSQL_DATABASE_TRAY: TrayWhatsDB (utilize ele pra criar o banco automaticamente)
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - minha_rede

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - minha_rede

  evolution_api:
    container_name: evolution_api
    environment:
      - DATABASE_PROVIDER=mysql  # Sem aspas, tudo minúsculo
      - DATABASE_URL=mysql://root:root@mysql:3306/evolution
      - DB_SKIP_MIGRATIONS=false
    image: atendai/evolution-api:v2.2.0
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy  
    command: sh -c "sleep 15 && npx prisma migrate deploy && node dist/main.js"
    networks:
      - minha_rede

  minha_api_node:
    container_name: minha_api_node
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true  # Ignora cache na construção
    ports:
      - "3001:3000"  # Escolha entre 3000 ou 3001, não ambos
    volumes:
      - ./src/backend:/usr/src/app/src/backend  # Mapeamento correto
      - /usr/src/app/node_modules
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=TrayWhatsDB
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  evolution_instances:
