version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evolution
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  evolution_api:  # <-- Observe que agora está alinhado com mysql e redis
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.0
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -c "sleep 10 && npx prisma migrate deploy && node dist/main.js"

volumes:
  mysql_data:
  redis_data:
  evolution_instances: